contact_links:
  - name: ğŸ“š Docs
    url: https://github.com/mountainash/deploy-to-vercel-action#-usage
    about: Checkout the documentation
  - name: ğŸš€ Feature Request
    url: https://github.com/mountainash/deploy-to-vercel-action/discussions/new?category=ideas
    about: Share ideas for new features
  - name: â“ Ask a Question
    url: https://github.com/mountainash/deploy-to-vercel-action/discussions/new?category=q-a
    about: Ask the community for help